#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
server:
  port: 2222
spring:
  application:
    name: user-service
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8761/user

